### ISSUE TITLE
Topbeat event frequency

### ISSUE THREAD

**Issue by ageis** [freedomofpress/ansible-role-logstash-client#6]
Right now the input `period` for topbeat is 10 seconds (`./templates/topbeat.yml.j2`). With multiple hosts over a length of time, this results in a lot of data filling up the ElasticSearch indices, and the granularity is more than necessary. We should update it to report the system state every minute instead. The period should also become a var so it can be dynamically adjusted.

**Comment by conorsch** [comment]
#7 broke the topbeat config; looks like we're not supposed to use quotes for the integer var. Fortunately the `validate` parameter caught the error and prevented updates on hosts in the wild.
